### ISSUE TITLE
Complete profile page 

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#12]
![image](https://github.com/ShivangM/workinn/assets/63797338/f5bcb61f-78ef-49b7-89b1-e458f20fce74)

Complete the Languages, Education, Skills, and Certifications section.
Server actions are created for CRUD operations you need to implement them and fetch data with Route APIs.

**Comment by Pranay-Thakre** [comment]
> ![image](https://user-images.githubusercontent.com/63797338/277154064-f5bcb61f-78ef-49b7-89b1-e458f20fce74.png)
> 
> Complete the Languages, Education, Skills, and Certifications section. Server actions are created for CRUD operations you need to implement them and fetch data with Route APIs.

I can do it. Assign it to me.

**Comment by ShivangM** [comment]
> > ![image](https://user-images.githubusercontent.com/63797338/277154064-f5bcb61f-78ef-49b7-89b1-e458f20fce74.png)
> > Complete the Languages, Education, Skills, and Certifications section. Server actions are created for CRUD operations you need to implement them and fetch data with Route APIs.
> 
> I can do it. Assign it to me.

OK

**Comment by wisdoms6969** [comment]
> ![image](https://github.com/ShivangM/workinn/assets/63797338/f5bcb61f-78ef-49b7-89b1-e458f20fce74)
> 
> 
> 
> Complete the Languages, Education, Skills, and Certifications section.
> 
> Server actions are created for CRUD operations you need to implement them and fetch data with Route APIs.
