### ISSUE TITLE
Complete Add Service Page

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#21]
The add service page will include:

1. Name of the service
2. Images (Can be multiple)
3. Description
4. Price
5. Faq's
6. Category
7. Subcategory (To be selected after category)
8. Service Category (To be selected after Sub-Category)
9. Sub-Service Category (To be selected after Service Category) [Optional]
10. Delivery Time
11. Requirements from buyers

Please let me know if you are confused with any of the above points.

This should be a simple form page and a single form for now.

**Comment by Pranay-Thakre** [comment]
Hi, Assign this to me. I can create this form.

**Comment by ShivangM** [comment]
Ok
