### ISSUE TITLE
Complete Service Page

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#22]
This is a page for an individual service that will include:

1. Name of the service
2. Images (Can be multiple)
3. Description
4. Price
5. Faq's
6. Category
7. Subcategory (To be selected after category)
8. Service Category (To be selected after Sub-Category)
9. Sub-Service Category (To be selected after Service Category) [Optional]
10. Delivery Time & Number of Revisions
11. Requirements from buyers
12. About Seller
13. Feedback and Reviews
14. Similar Services
15. Message Seller

Some Sections can be static for now but divide the page into components and keep the UI clean.

**Comment by shivanginikumar03** [comment]
Hi assign this to me please.

**Comment by ShivangM** [comment]
Ok, please note that service fetch will be available now, I will update the page for you so that you get a service to work with and complete the page.
