### ISSUE TITLE
Create Become a Seller Page.

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#5]
This page is for sellers to get started when they are not logged in. You have to create a start-selling page including information about services created till now, and their price ranges. Some sellers and their images, how selling works, Buyers stories, some Q&A and CTA. As data is not available create a JSON file and temporary data for sections.

Take this page as a reference: https://www.fiverr.com/start_selling?source=top_nav

**Comment by Pranay-Thakre** [comment]
Assign this to me please.

**Comment by ShivangM** [comment]
> Assign this to me please.

Sure
