### ISSUE TITLE
Create Explore Page

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#6]
This page includes all the categories that a user can explore. Like: Web Services, Graphics and Design, AI, etc. You have to display all these categories and on clicking them, the user should be directed to a specific category page that will include all the subcategories. The page should have a simple UI and be easy to use, The category card can include a name, description, and image for the category.

**Comment by shivanginikumar03** [comment]
Please assign this issue to me.

**Comment by ShivangM** [comment]
> Please assign this issue to me.

Ok

**Comment by SathvikKandadi** [comment]
Hey I am new to open source .Can you assign this issue to me?

**Comment by ShivangM** [comment]
> Hey I am new to open source . Can you assign this issue to me?

Sorry, but the task is already being assigned. I will let you know if there are any more tasks for you. Keep checking the Issue tab.
