### ISSUE TITLE
Create User Profile Page

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#7]
A user profile page is needed, to fetch user data from API provided and then create a profile page to display details and edit Details. The profile page will contain details including Name, Image, Description, Languages, Skills, education, certifications, country, and member since. It should be minimalistic.

Services by users should also be mentioned on the profile and if the user has some feedback then it too.

**Comment by shivanginikumar03** [comment]
Assign this to me.

**Comment by ShivangM** [comment]
> Assign this to me.

Done
