### ISSUE TITLE
Redirect user to login route on unauthorized access

### ISSUE THREAD

**Issue by ShivangM** [ShivangM/workinn#9]
The task is to redirect users to log in when they try to visit a protected route without login. This has to be done with the help of next js middleware and token cookies.

**Comment by vikaspatil0021** [comment]
Hey can you list protected routes

**Comment by AKACHI-4** [comment]
> Hey can you list protected routes

Yah ... I'd like to know which protected routes u're referring to.

**Comment by ShivangM** [comment]
> Hey can you list protected routes

All routes under:

1. profile
2. dashboard
3. settings
4. billings-payments
5. refer-friend

Create a middleware file in the root directory and you need to check for a "token" cookie, if it exists then allow users to go to these routes otherwise redirect them to log in.

only work on the middleware.ts file in the root.

You will need to set your own Firebase project and environment with the template:

//Firebase
NEXT_PUBLIC_FIREBASE_API_KEY = 
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = 
NEXT_PUBLIC_FIREBASE_PROJECT_ID = 
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = 
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = 
NEXT_PUBLIC_FIREBASE_APP_ID =
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = 

FIREBASE_SERVICE_ACCOUNT_KEY = Service account json as string, without line breaks

**Comment by shivanginikumar03** [comment]
Assign this to me please, I am beginner and interested in open source.

> > Hey can you list protected routes
> 
> All routes under:
> 
> 1. profile
> 2. dashboard
> 3. settings
> 4. billings-payments
> 5. refer-friend
> 
> Create a middleware file in the root directory and you need to check for a "token" cookie, if it exists then allow users to go to these routes otherwise redirect them to log in.
> 
> only work on the middleware.ts file in the root.
> 
> You will need to set your own Firebase project and environment with the template:
> 
> //Firebase NEXT_PUBLIC_FIREBASE_API_KEY = NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = NEXT_PUBLIC_FIREBASE_PROJECT_ID = NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = NEXT_PUBLIC_FIREBASE_APP_ID = NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID =
> 
> FIREBASE_SERVICE_ACCOUNT_KEY = Service account json as string, without line breaks

**Comment by ShivangM** [comment]
If the user is already logged in then you have to redirect them to the home page if they are visiting the signing page.
